b140910053/b140910053/ayku/ayku/Controllers/UyeGirisController.cs
using ayku.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ayku.Controllers
{
    public class UyeGirisController : Controller
    {
        // GET: UyeGiris
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Giris(UyeGirisModel model)
        {
            KediEviEntities db = new KediEviEntities();
            
           
                foreach (var uye in db.Uyeler)
                {
                    if (uye.email == model.email && uye.sifre == model.sifre) // Formdaki Veriler veritabanıyla eşleşiyorsa
                    {
                        if(uye.adsoyad=="admin" && uye.email=="admin@admin.com")
                        {
                            Session["adsoyad"] = uye.adsoyad;
                            Session["admin"] = uye.adsoyad;
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            Session["adsoyad"] = uye.adsoyad;           //Session oluşur ve anasayfaya yönlendirir
                            Session["id"] = uye.id; 
                            return RedirectToAction("Index", "Home");
                        }
                        
                    }                  
                }
            
            return RedirectToAction("Index");
        }
        public ActionResult Cikis()
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "Home");
        }
    }
}

b140910053/b140910053/ayku/ayku/Views/UyeGiris/Index.cshtml
@model ayku.Models.UyeGirisModel
@{
    ViewBag.Title = "Giriş";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Üye Giriş</h2>

@using (Html.BeginForm("Giris","UyeGiris"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Giriş" class="btn btn-default" />
            </div>
        </div>
    </div>
    
    
    
}