b140910053/b140910053/ayku/ayku/Controllers/LANGUAGEController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ayku.Controllers
{
    public class LANGUAGEController : Controller
    {
        // GET: LANGUAGE
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Change(string languageabbrevation)
        {
            if (languageabbrevation != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageabbrevation);
                Thread.CurrentThread.CurrentUICulture =  new CultureInfo(languageabbrevation);
       
            }
            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageabbrevation;
            Response.Cookies.Add(cookie);
            return View("Index");
        
        }
    }
}

b140910053/b140910053/ayku/ayku/Controllers/UyelerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ayku.Models;

namespace ayku.Controllers
{
    public class UyelerController : Controller
    {
        private KediEviEntities db = new KediEviEntities();

        // GET: Uyeler
        public ActionResult Index()
        {
            if (Session["admin"] == null) //admin girişi olmadıgında adres cubugundan erişmemek için
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(db.Uyeler.ToList());
            }
            
        }
  
        public ActionResult UyeEkle()
        {
            return View();
        }

        
       
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UyeEkle([Bind(Include = "id,adsoyad,email,sifre")] Uyeler uyeler)
        {
            if (ModelState.IsValid)
            {
                db.Uyeler.Add(uyeler);
                db.SaveChanges();
                return RedirectToAction("Index","UyeGiris");
            }

            return View(uyeler);
        }

        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uyeler uyeler = db.Uyeler.Find(id);
            if (uyeler == null)
            {
                return HttpNotFound();
            }
            return View(uyeler);
        }

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle([Bind(Include = "id,adsoyad,email,sifre")] Uyeler uyeler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uyeler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uyeler);
        }


        public ActionResult Sil(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uyeler uyeler = db.Uyeler.Find(id);
            if (uyeler == null)
            {
                return HttpNotFound();
            }
            return View(uyeler);
        }

        // POST: Uyeler/Delete/5
        [HttpPost, ActionName("Sil")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uyeler uyeler = db.Uyeler.Find(id);
            db.Uyeler.Remove(uyeler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

b140910053/b140910053/ayku/ayku/Controllers/iletisimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ayku.Models;

namespace ayku.Controllers
{
    public class iletisimController : Controller
    {
        private KediEviEntities db = new KediEviEntities();

     
  

        // GET: iletisims/Create
        public ActionResult iletisim()
        {
            return View();
        }

        // POST: iletisims/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult iletisim([Bind(Include = "iletisimID,ad,eposta,telefon,iletiniz")] iletisim iletisim)
        {
            if (ModelState.IsValid)
            {
                db.iletisim.Add(iletisim);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(iletisim);
        }

     


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

b140910053/b140910053/ayku/ayku/Controllers/urunIstekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ayku.Models;

namespace ayku.Controllers
{
    public class urunIstekController : Controller
    {
        private KediEviEntities db = new KediEviEntities();

       

        // GET: urunIstek/Create
        public ActionResult Index()
        {
            ViewBag.id = new SelectList(db.Uyeler, "id", "adsoyad");
            return View();
        }

        // POST: urunIstek/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "istekID,id,mesaj")] urunIstek urunIstek)
        {
            if (ModelState.IsValid)
            {
                db.urunIstek.Add(urunIstek);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id = new SelectList(db.Uyeler, "id", "adsoyad", urunIstek.id);
            return View(urunIstek);
        }

     
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

b140910053/b140910053/ayku/ayku/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=2.0">
    <title>@ViewBag.Title - KediEvi</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbar-> 
        <div class="container">
            <div class="navbar-header">
                <img src="~/resim/kedilogo.jpg" alt="KEDİ EVİ" class="img-rounded" height="50" with="50" border="0">
                <b>@Html.ActionLink(ayku.cokludil.dil.KEDİEVİ, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</b>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" >
                    
                    <li>@Html.ActionLink(ayku.cokludil.dil.Kedilerhakkında, "kedilerhakkinda", "Home")</li>
                    <li>@Html.ActionLink(ayku.cokludil.dil.KediShop, "kedishop", "Home")</li>
                    <li>@Html.ActionLink(ayku.cokludil.dil.Barınaklar, "barinaklar", "Home")</li>
                    <li>@Html.ActionLink(ayku.cokludil.dil.Hakkımızda, "About", "Home")</li>
                    <li>@Html.ActionLink(ayku.cokludil.dil.İletişim, "iletisim", "iletisim")</li>
                    <li>@Html.ActionLink(ayku.cokludil.dil.Dİl,"Index","LANGUAGE")</li>
                    @if (Session["adsoyad"] == null)
                    {
                        <li>@Html.ActionLink("Üye Kayıt", "UyeEkle", "Uyeler")</li>
                        <li>@Html.ActionLink("Giriş", "Index", "UyeGiris")</li>
                    }
                    else
                    {
                        <li><br /><font style="color:white">HOŞGELDİN <b>@Session["adsoyad"]</b></font></li>
                        if (Session["admin"] != null)
                        {
                            <li>@Html.ActionLink("Admin Paneli", "Index", "Uyeler")</li>                          
                            <li>@Html.ActionLink("Çıkış", "Cikis", "UyeGiris")</li>
                        }
                        else
                        { 
                        <li>@Html.ActionLink("Ürün İstek Formu", "Index", "urunIstek")</li>
                        <li>@Html.ActionLink("Çıkış", "Cikis", "UyeGiris")</li>
                        }  
                    }      
                </ul>
                
            </div>
        </div>

    
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KEDİ EVİ</p>
        </footer>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-buttom>
        <div class=" container">
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a href="https://www.facebook.com/Kedi-diyar%C4%B1-357124467802143/" target=new><img src="http://in.sitekodlari.com/fb/facebook6.png"height="30" border="0"></a>
            <li><a href="https://www.instagram.com/kedi_sahiplendirme/" target=new><img src="http://in.sitekodlari.com/insta/4.png" height="30" border="0"></a>
            <li><a href="https://twitter.com/KediSahiplendir" target=new><img src="http://in.sitekodlari.com/tw/8.png" height="30" border="0"></a>
        </ul>
    </div>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>